require:
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Style/ClassAndModuleChildren:
  Include:
    - 'test/**/*.rb'
  EnforcedStyle: compact

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'test/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
