version: 2.1
executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

jobs:
  build:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          key: shacip-alpha-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install --deployment

      - save_cache:
          key: shacip-alpha-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: bin/rails db:setup --trace

      - run:
          name: Running Tests
          command: bin/rails test --verbose --ci-report

      - store_test_results:
          path: test/reports

  lint:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          key: shacip-alpha-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install --deployment

      - save_cache:
          key: shacip-alpha-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Running Linter
          command: bin/rails rubocop:linter

workflows:
  testing:
    jobs:
      - build
      - lint
